GET http://localhost:3000
Authorization: Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2M2M1MGVhZjM5OTFmNDNmNzYyMGRkNmMiLCJpc3MiOiJhc2ltLmNvbSIsImlhdCI6MTY3NDAyNjg5NSwiZXhwIjoxNjc0MDI2OTI1fQ.r5xNJ_DAVWVjn9MO37UrBHyi7iUh3MpT_Je11drS5-0


###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"password"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"password"
}


###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2M2M1MGVhZjM5OTFmNDNmNzYyMGRkNmMiLCJpc3MiOiJhc2ltLmNvbSIsImlhdCI6MTY3NDAzMTQyNSwiZXhwIjoxNzA1NTg5MDI1fQ.4aB1_89qQW6a008LwUtj8wWoMVBojX1QXxfj1Jn-e_A"
}



###
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2M2M1MGVhZjM5OTFmNDNmNzYyMGRkNmMiLCJpc3MiOiJhc2ltLmNvbSIsImlhdCI6MTY3NDAzMTQyNSwiZXhwIjoxNzA1NTg5MDI1fQ.4aB1_89qQW6a008LwUtj8wWoMVBojX1QXxfj1Jn-e_A"
}